# Generated by Django 5.1.3 on 2024-11-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='workdetails',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
