# Generated by Django 5.1.3 on 2024-11-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_worksite_workdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='in', max_length=50),
        ),
    ]
