# Generated by Django 5.1.3 on 2024-11-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_employee_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daywisereport',
            old_name='site_name',
            new_name='worksite_name',
        ),
    ]
