# Generated by Django 5.1.3 on 2024-11-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_rename_site_name_daywisereport_worksite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendance',
            field=models.CharField(choices=[('Precent', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10),
        ),
    ]
