# Generated by Django 5.1.3 on 2024-12-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_alter_employeeattendance_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
