# Generated by Django 5.1.3 on 2024-12-28 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0006_site_remarks_site_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='c_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='c_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
