# Generated by Django 5.1.3 on 2024-12-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0007_site_c_date_site_c_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
