# Generated by Django 5.1.3 on 2024-12-29 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0008_employee_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='daywisereport',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'status': 'in'}, on_delete=django.db.models.deletion.CASCADE, to='siteapp.employee'),
        ),
    ]
