# Generated by Django 5.1.3 on 2024-12-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0009_daywisereport_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='remarks',
            field=models.CharField(blank=True, max_length=1005, null=True),
        ),
    ]
