# Generated by Django 5.1.3 on 2024-12-30 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0010_alter_employee_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.employee'),
        ),
    ]
