# Generated by Django 5.1.3 on 2025-01-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0011_alter_employeeattendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='daywisereport',
            name='remarks',
            field=models.CharField(blank=True, max_length=1005, null=True),
        ),
    ]
