# Generated by Django 5.1.3 on 2025-01-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0012_daywisereport_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
