# Generated by Django 5.1.3 on 2025-01-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0013_worksite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='workdetails',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
