# Generated by Django 5.1.3 on 2025-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0014_alter_worksite_workdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
