# Generated by Django 5.0 on 2025-01-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0015_alter_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='materials',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
