# Generated by Django 5.1.3 on 2025-01-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0016_site_materials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-id']},
        ),
    ]
