# Generated by Django 5.1.3 on 2025-01-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0017_alter_site_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daywisereport',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='worksite',
            options={'ordering': ['-id']},
        ),
    ]
