# Generated by Django 6.0.1 on 2026-01-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0018_alter_daywisereport_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daywisereport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={},
        ),
    ]
